"""Script to get the number of movies per country"""

import sys
import pandas as pd
import matplotlib.pyplot as plt


def main():
    """Main entry point for the script."""
    input_file = 'output/movie-countries-20m.csv'
    output_file = 'output/country-stats-20m.csv'

    # open the movie-countries csv generated by getCountryData.py
    input_file = pd.read_csv(input_file, keep_default_na=False)

    # get the number of movie entries we have
    num_movies = input_file.shape[0]

    # declarations for dictionaries
    country_count_dict = {}
    country_count_primary_dict = {}

    # iterate through the rows
    for i in range(0, num_movies):
        # get the countries associated with a movie
        countries = input_file.country[i].split("|")

        # some movies have more than one country associated with them (i.e. USA|UK)
        for country in countries:
            # count all countries
            country_count_dict[country] = country_count_dict.get(country, 0) + 1

            # count all primary countries in separate dictionary (if it's the first country listed)
            if country == countries[0]:
                country_count_primary_dict[country] = country_count_primary_dict.get(country, 0) + 1

    # dataframe for basic count
    df = pd.DataFrame(list(country_count_dict.iteritems()), columns=['country', 'count'])

    # dataframe for primary count
    df2 = pd.DataFrame(list(country_count_primary_dict.iteritems()), columns=['country', 'primary_count'])

    # merge the two dataframes on 'country'
    result = pd.merge(df, df2, on='country')

    # sort
    sorted_result = result.sort_values(['country'])

    # add some percentage data
    sorted_result['count_percentage'] = sorted_result['count'] / sorted_result['count'].sum()
    sorted_result['primary_percentage'] = sorted_result['primary_count'] / sorted_result['primary_count'].sum()

    # write to CSV
    sorted_result.to_csv(output_file, index=False)

    # plot
    axes = sorted_result.plot(x='country', y='count_percentage', kind='bar', title='Number of Movies from a Country',
                              legend=False)

    # set the axes and set display
    axes.set_xlabel("Country")
    axes.set_ylabel("Count")
    plt.tight_layout()
    plt.show()

if __name__ == '__main__':
    sys.exit(main())
